sonatel:
  my-msisdn: 771292773
  my-pin-code: 2021

######################################    ######################################
                 ################ CONFIGURATION PROPERTIES    #############
######################################    ######################################

server.port: 8080
