sonatel:
  base-url: https://api.orange-sonatel.com
  security:
    client-id:
    client-secret:
  retailer:
    msisdn: 77XXXXXXX
    pin-code: XXXX
  merchant:
    msisdn: 77XXXXXXX
    merchant-code: "123456"
    pin-code: XXXX