sonatel:
  base-url: https://api.sandbox.orange-sonatel.com
  public-key-uri: /api/account/v1/publicKeys
  security:
    client-id: a2b89020-b832-42ed-9dff-a36df4194ed7
    client-secret: 22c4f5d0-aa7b-4d76-aab4-f8188edda220
  my-msisdn: 771292773
  my-pin-code: 2021




######################################    ######################################
                 ################ CONFIGURATION PROPERTIES    #############
######################################    ######################################

server.port: 8080

spring:
  profiles:
    default: sandbox
  application.name: sonatel-api-demo
  #main.web-application-type: servlet
  security.oauth2.client:
    registration:
      sonatel:
        client-id: ${sonatel.security.client-id}
        client-secret: ${sonatel.security.client-secret}
        authorization-grant-type: client_credentials
        scope: email
    provider:
      sonatel:
        token-uri: ${sonatel.base-url}/oauth/v1/token
